Tests
opencomponents/oc-template-handlebars pull request #4
Opened 2017-01-25 15:02 UTC by nickbalestra

2017-01-25 15:39 UTC, matteofigus requested changes

2017-01-25 15:39 UTC, matteofigus commented on test/utils.spec.js
> +    const result = utils.validator('', 'jade');
Why the utils.validate signature has even the type param? This module should just be about handlebars?

2017-01-25 15:39 UTC, matteofigus commented on package.json
> +    "ghooks": "^2.0.0",
what is ghooks for?

2017-01-25 15:39 UTC, matteofigus commented on .travis.yml
> +  - secure: P/+5dvk3zwkDnUmNCEX8fgNkLAQ5s6j+dR4h3Zn5UJBBUKSZaz1QbfEX+uZ5Rn4l4aRGdvG2PGStySiS/MHmPKhWJfMMEkSFjERLUF07U2gLSkn1UOQeh0zBWIb5TehwIuuTNPmOoSE/7xgmXwF83Dq8ALjDCmo6VrtoZes9E2g=
Why do we need the secure params?

2017-01-25 18:10 UTC, nickbalestra commented on package.json
> +    "ghooks": "^2.0.0",
git hooks. 
using it to run test before commit :)

2017-01-25 18:11 UTC, nickbalestra commented on .travis.yml
> +  - secure: P/+5dvk3zwkDnUmNCEX8fgNkLAQ5s6j+dR4h3Zn5UJBBUKSZaz1QbfEX+uZ5Rn4l4aRGdvG2PGStySiS/MHmPKhWJfMMEkSFjERLUF07U2gLSkn1UOQeh0zBWIb5TehwIuuTNPmOoSE/7xgmXwF83Dq8ALjDCmo6VrtoZes9E2g=
we don't 👍

2017-01-30 12:26 UTC, nickbalestra commented
fixes #2 #1

2017-01-30 12:29 UTC, matteofigus approved these changes

2017-01-30 12:29 UTC, merged